// index.js
const cloud = require('wx-server-sdk');
const axios = require('axios');

cloud.init({
  env: cloud.DYNAMIC_CURRENT_ENV
});

exports.main = async (event, context) => {
  const { text, lang = 'zh' } = event;

  if (!text) {
    return { error: true, message: '输入文本不能为空' };
  }

  // 从环境变量获取配置
  const apiKey = process.env.LLM_API_KEY;
  const apiUrl = process.env.LLM_API_URL || 'https://api.openai.com/v1/chat/completions';
  const modelName = process.env.LLM_MODEL || 'gpt-4o-mini';

  if (!apiKey) {
    console.error('环境变量 LLM_API_KEY 未配置');
    return { error: true, errorType: 'model_error', message: '服务未正确配置' };
  }

  try {
    let prompt = '';
    
    if (lang === 'en') {
      prompt = `You are an intelligent shopping assistant. Please extract the shopping list from the user's natural language input.
The input might describe ingredients directly (e.g. "I want to buy apples"), or describe a dish they want to cook (e.g. "I want to make Sweet and Sour Pork").
CRITICAL INSTRUCTION 1: If the user mentions a DISH/RECIPE name or a PROPER NOUN DISH (like "Buddha Jumps Over the Wall", "Peking Duck", "Sweet and Sour Pork", "Spicy Crayfish"), DO NOT just return the dish name as an ingredient! You MUST accurately identify it as a [Dish] and break down that dish into its essential raw ingredients (e.g., Buddha Jumps Over the Wall requires: Abalone, Sea Cucumber, Fish Maw, Scallops, Pork Ribs, Quail Eggs, etc.) and list them as individual items, and you MUST set their "sourceRecipe" field to the dish name. Even if the name sounds like a single item, if it is a well-known dish, it must be broken down.
CRITICAL INSTRUCTION 2: The input might be generated by a Speech-to-Text (STT) engine or typing with typos, so it may contain HOMOPHONE ERRORS or slight misrecognitions (e.g. "screaming tofu" instead of "green pepper tofu"). You MUST use your reasoning to correct these phonetic typos based on the culinary context before extracting the list.
CRITICAL INSTRUCTION 3: DISTINGUISHING DISHES VS STANDALONE INGREDIENTS. If the user's input is a list of standalone ingredients (e.g., "apples, bananas", "I need potatoes and a fish"), treat them ALL as STANDALONE ingredients. DO NOT hallucinate or guess a dish name for them! Leave their "sourceRecipe" as an empty string "". However, if the user inputs MULTIPLE DISH NAMES (e.g., "Sweet and Sour Pork, Peking Duck"), you MUST treat EACH of them as a dish and break them down respectively into ingredients, assigning their respective "sourceRecipe".
CRITICAL INSTRUCTION 4: Regardless of the language of the user's input, you MUST translate and output ALL extracted values (including ingredient names, dish names, categories, etc.) strictly in ENGLISH.

If the user's input is completely unrelated to food, recipes, or shopping, please return an empty JSON array [].

User Input: "${text}"

Please output a pure JSON array, where each element is an object with the following fields:
- "name": (String) The exact name of the ingredient (NOT the dish name).
- "standardName": (String) The same as "name".
- "category": (String) Supermarket aisle category, choose from: "Seafood, Meat & Eggs", "Fresh Produce", "Grains, Oils & Condiments", "Others".
- "sourceRecipe": (String) If this ingredient belongs to a specific dish, put the CORRECTED DISH NAME here. If the user is purely listing standalone ingredients without implying any dish, leave it as an empty string "".

Return ONLY JSON array. Do not include any other text or markdown wrappers like \`\`\`json. Output all values in English.`;
    } else {
      prompt = `你是一个老练的名厨，做了无数名菜，也吃遍全世界，也非常喜欢逛菜市场，不论什么菜名，你脑子里一定能马上浮现对应需要的完整食材清单。请从用户的自然语言输入中提取采购清单。
用户可能会直接说要买什么食材（例如“买苹果”），也可能会说要做某道菜（例如“做个夫妻肺片”或“辣炒香螺”）。
【核心指令 1】：如果用户提到的是“菜谱名”、“专有名词菜品”（如“佛跳墙”、“夫妻肺片”、“北京烤鸭”、“麻婆豆腐”、“麻辣小龙虾”），绝对不要把菜名本身当作一个要买的商品！你必须准确识别出这属于【菜品】，并将这道菜拆解成做这道菜所需的“基础生鲜食材和调料”（例如做佛跳墙需要：鲍鱼、海参、花胶、干贝、排骨、鹌鹑蛋【等】），并将这些拆解后的具体食材作为独立的商品项返回，并且它们的 sourceRecipe 字段必须全部填上这道菜的名称。即使名字听起来像一个物品，只要它是知名菜品，就必须进行拆解。一定要拆的准、拆的细。
【核心指令 2】：用户的输入极大概率来自于“语音转文字（语音识别）”或“拼音输入”，因此文本中难免会包含【错别字】或【同音字错误】（例如把“尖椒干豆腐”识别或打成“尖叫干豆腐”）。你必须结合烹饪、食材和日常购物的上下文，智能纠正这些错别字，然后再进行食材拆解。
【核心指令 3】：区分“纯食材”与“菜品组合”。如果用户输入的是一连串纯粹的食材（例如“苹果、香蕉”、“买点土豆，还要一条鱼”），请务必将它们作为【独立食材】处理，它们的 sourceRecipe 必须严格留空字符串 ""！但是，如果用户输入了多个“菜名”（例如“蚂蚁上树，鱼香肉丝，尖椒干豆腐，番茄龙利鱼”），你必须将它们分别识别为【菜品】并逐个拆解为做该菜所需的食材，同时为这些食材分别填上对应的 sourceRecipe（正确的菜名）。
【核心指令 4】：无论用户输入的原本是什么语言，你都必须将所有提取出的菜名、食材名、分类等信息翻译并严格用【中文】输出。

如果用户的输入与食材、菜谱或购物完全无关，请返回空数组 []。

用户输入：“${text}”

请输出一个纯JSON数组，数组中的每个元素是一个对象，包含以下字段：
- "name": (字符串) 具体的食材名称（绝对不能是菜名本身）。
- "standardName": (字符串) 和 name 保持一致。
- "category": (字符串) 超市动线分类，请严格从以下选项中选择：["鱼鲜肉蛋", "生鲜蔬果", "粮油配料", "其他"]。
- "sourceRecipe": (字符串) 如果这个食材是为了做某道菜，请在这里填入【纠正错别字后的正确菜名】。极其重要：只要用户输入的是菜品名（哪怕没有带“做”字，例如只输入“麻辣小龙虾”或“佛跳墙”），就必须把该菜名填到这里！用于后续按菜谱分组！如果用户输入的纯粹只是罗列独立食材（例如“买点苹果和香蕉”），才留空字符串 ""。

只返回JSON数组，不要包含任何其他说明文字，也不要用Markdown代码块包裹。所有内容请用中文输出。`;
    }

    const messages = [
      { role: 'user', content: prompt }
    ];

    const response = await axios.post(apiUrl, {
      model: modelName,
      messages: messages,
      temperature: 0.3, // 低温度，确保输出结构化和稳定性
      max_tokens: 2000 // 限制最大返回token数，扩大到2000以支持多道菜品同时拆解
    }, {
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`
      },
      timeout: 60000 // 增加 axios 请求超时时间到 60 秒
    });

    let content = response.data.choices[0].message.content;
    content = content.replace(/^```json\s*/i, '').replace(/```\s*$/i, '').trim();

    let resultData;
    try {
      resultData = JSON.parse(content);
    } catch (parseErr) {
      console.error('模型返回解析失败', content);
      return { error: true, errorType: 'model_error', message: '提取失败，请重试' };
    }

    return {
      error: false,
      data: resultData
    };

  } catch (err) {
    console.error('LLM 请求失败:', err.response ? err.response.data : err.message);
    return { error: true, errorType: 'network_error', message: '网络请求失败，请稍后重试' };
  }
};
