module.exports = {
  // Global
  app_name: 'Mercadista',
  app_slogan: 'Elevate Your Everyday Market Finds',
  lang_switch: '中',
  tab_home: 'Home',
  tab_list: 'List',
  tab_my: 'Profile',
  page_title_list: 'Shopping List',
  
  list_merge_confirm_content: 'AI thinks [{source}] and [{target}] might be the same. Merge into [{target}] or [Keep Separate]?',
  list_merge_confirm_yes: 'Merge',
  list_merge_confirm_no: 'Keep Separate',
  list_add_recipe_title: 'Add Recipe/Dish',
  list_add_recipe_placeholder: 'Enter name (e.g. Tomato Egg)',
  list_edit_ingredient_title: 'Edit Ingredient',
  list_edit_ingredient_placeholder: 'Enter new ingredient name',
  list_delete_recipe_confirm: 'Are you sure to delete all ingredients in 【{recipe}】?',
  list_independent_ingredients: 'Independent Ingredients',
  list_other_ingredients: 'Others',
  list_direct_add: 'Direct Add',
  my_batch_delete_confirm: 'Are you sure to delete the selected {count} items?',
  my_rename_title: 'Rename',
  my_rename_placeholder: 'Enter new name',
  my_clear_tab_execution: 'all shopping lists',
  my_clear_tab_planning: 'all favorite recipes',
  my_clear_tab_collection: 'all ingredient stamps',
  my_clear_tab_confirm: 'Are you sure to clear {tabName}? This cannot be undone.',
  // Index Page
  camera_title: 'Snap to Identify',
  camera_desc: 'Identify · Check Freshness · Get Recipes',
  album_entry: 'Album',
  transition_identify: 'Identify',
  transition_list: 'Make List',
  list_progress_title: "Today's Shopping List",
  list_progress_desc: '{bought} / {total} bought',
  swipe_guide: 'Never miss an item',
  fab_note: 'Add Note',
  analyzing_title: 'Analyzing Ingredient...',
  analyzing_hint: 'Dazzled by the choices! Give me 15-30s to take a closer look...',
  index_stop_record: 'Tap to stop recording',
  index_generate_list: 'Generate List',
  index_ai_processing: 'AI Chef is processing, please wait',
  index_quick_record: '📝 Quick Record',
  index_record_placeholder: 'Enter a recipe (e.g. Spanish paella) or ingredients (e.g. 3 tomatoes)...',
  index_generate_btn: 'Generate List',
  
  // Onboarding
  onboarding_title: 'Welcome to Mercadista',
  onboarding_subtitle: 'To provide you with smarter and more personalized services, we need the following information and permissions:',
  onboarding_profile_title: 'Basic Profile',
  onboarding_profile_desc: 'Used for personalized display of your personal page.',
  onboarding_culture_title: 'Food Culture',
  onboarding_culture_desc: 'Recommend recipes that better suit your taste based on your background.',
  onboarding_location_title: 'Location',
  onboarding_location_desc: 'Get your fuzzy location to recommend local recipes.',
  onboarding_record_title: 'Microphone',
  onboarding_record_desc: 'Support quick ingredient input via voice.',
  onboarding_btn_auth: 'Authorize',
  onboarding_btn_authed: 'Authorized',
  onboarding_btn_enter: 'Start Experience',
  onboarding_require_all: 'Please complete all info and permissions above',
  onboarding_input_nickname: 'Enter nickname',
  onboarding_select_nationality: 'Select your nationality',
  onboarding_fuzzy_location: 'Fuzzy Location',
  onboarding_mic_record: 'Microphone',
  onboarding_btn_save: 'Save Settings',

  // Nationality
  nationality_title: 'Nationality',
  nationality_list: [
    { id: 'cn', name: 'China' },
    { id: 'us', name: 'United States' },
    { id: 'gb', name: 'United Kingdom' },
    { id: 'jp', name: 'Japan' },
    { id: 'kr', name: 'South Korea' },
    { id: 'fr', name: 'France' },
    { id: 'de', name: 'Germany' },
    { id: 'it', name: 'Italy' },
    { id: 'es', name: 'Spain' },
    { id: 'ru', name: 'Russia' },
    { id: 'th', name: 'Thailand' },
    { id: 'in', name: 'India' },
    { id: 'af', name: 'Afghanistan' },
    { id: 'ax', name: 'Åland Islands' },
    { id: 'al', name: 'Albania' },
    { id: 'dz', name: 'Algeria' },
    { id: 'as', name: 'American Samoa' },
    { id: 'ad', name: 'Andorra' },
    { id: 'ao', name: 'Angola' },
    { id: 'ai', name: 'Anguilla' },
    { id: 'aq', name: 'Antarctica' },
    { id: 'ag', name: 'Antigua & Barbuda' },
    { id: 'ar', name: 'Argentina' },
    { id: 'am', name: 'Armenia' },
    { id: 'aw', name: 'Aruba' },
    { id: 'au', name: 'Australia' },
    { id: 'at', name: 'Austria' },
    { id: 'az', name: 'Azerbaijan' },
    { id: 'bs', name: 'Bahamas' },
    { id: 'bh', name: 'Bahrain' },
    { id: 'bd', name: 'Bangladesh' },
    { id: 'bb', name: 'Barbados' },
    { id: 'by', name: 'Belarus' },
    { id: 'be', name: 'Belgium' },
    { id: 'bz', name: 'Belize' },
    { id: 'bj', name: 'Benin' },
    { id: 'bm', name: 'Bermuda' },
    { id: 'bt', name: 'Bhutan' },
    { id: 'bo', name: 'Bolivia' },
    { id: 'ba', name: 'Bosnia & Herzegovina' },
    { id: 'bw', name: 'Botswana' },
    { id: 'bv', name: 'Bouvet Island' },
    { id: 'br', name: 'Brazil' },
    { id: 'io', name: 'British Indian Ocean Territory' },
    { id: 'vg', name: 'British Virgin Islands' },
    { id: 'bn', name: 'Brunei' },
    { id: 'bg', name: 'Bulgaria' },
    { id: 'bf', name: 'Burkina Faso' },
    { id: 'bi', name: 'Burundi' },
    { id: 'kh', name: 'Cambodia' },
    { id: 'cm', name: 'Cameroon' },
    { id: 'ca', name: 'Canada' },
    { id: 'cv', name: 'Cape Verde' },
    { id: 'bq', name: 'Caribbean Netherlands' },
    { id: 'ky', name: 'Cayman Islands' },
    { id: 'cf', name: 'Central African Republic' },
    { id: 'td', name: 'Chad' },
    { id: 'cl', name: 'Chile' },
    { id: 'cx', name: 'Christmas Island' },
    { id: 'cc', name: 'Cocos (Keeling) Islands' },
    { id: 'co', name: 'Colombia' },
    { id: 'km', name: 'Comoros' },
    { id: 'cg', name: 'Congo - Brazzaville' },
    { id: 'cd', name: 'Congo - Kinshasa' },
    { id: 'ck', name: 'Cook Islands' },
    { id: 'cr', name: 'Costa Rica' },
    { id: 'ci', name: 'Côte d’Ivoire' },
    { id: 'hr', name: 'Croatia' },
    { id: 'cu', name: 'Cuba' },
    { id: 'cw', name: 'Curaçao' },
    { id: 'cy', name: 'Cyprus' },
    { id: 'cz', name: 'Czechia' },
    { id: 'dk', name: 'Denmark' },
    { id: 'dj', name: 'Djibouti' },
    { id: 'dm', name: 'Dominica' },
    { id: 'do', name: 'Dominican Republic' },
    { id: 'ec', name: 'Ecuador' },
    { id: 'eg', name: 'Egypt' },
    { id: 'sv', name: 'El Salvador' },
    { id: 'gq', name: 'Equatorial Guinea' },
    { id: 'er', name: 'Eritrea' },
    { id: 'ee', name: 'Estonia' },
    { id: 'sz', name: 'Eswatini' },
    { id: 'et', name: 'Ethiopia' },
    { id: 'fk', name: 'Falkland Islands' },
    { id: 'fo', name: 'Faroe Islands' },
    { id: 'fj', name: 'Fiji' },
    { id: 'fi', name: 'Finland' },
    { id: 'gf', name: 'French Guiana' },
    { id: 'pf', name: 'French Polynesia' },
    { id: 'tf', name: 'French Southern Territories' },
    { id: 'ga', name: 'Gabon' },
    { id: 'gm', name: 'Gambia' },
    { id: 'ge', name: 'Georgia' },
    { id: 'gh', name: 'Ghana' },
    { id: 'gi', name: 'Gibraltar' },
    { id: 'gr', name: 'Greece' },
    { id: 'gl', name: 'Greenland' },
    { id: 'gd', name: 'Grenada' },
    { id: 'gp', name: 'Guadeloupe' },
    { id: 'gu', name: 'Guam' },
    { id: 'gt', name: 'Guatemala' },
    { id: 'gg', name: 'Guernsey' },
    { id: 'gn', name: 'Guinea' },
    { id: 'gw', name: 'Guinea-Bissau' },
    { id: 'gy', name: 'Guyana' },
    { id: 'ht', name: 'Haiti' },
    { id: 'hm', name: 'Heard & McDonald Islands' },
    { id: 'hn', name: 'Honduras' },
    { id: 'hk', name: 'Hong Kong SAR China' },
    { id: 'hu', name: 'Hungary' },
    { id: 'is', name: 'Iceland' },
    { id: 'id', name: 'Indonesia' },
    { id: 'ir', name: 'Iran' },
    { id: 'iq', name: 'Iraq' },
    { id: 'ie', name: 'Ireland' },
    { id: 'im', name: 'Isle of Man' },
    { id: 'il', name: 'Israel' },
    { id: 'jm', name: 'Jamaica' },
    { id: 'je', name: 'Jersey' },
    { id: 'jo', name: 'Jordan' },
    { id: 'kz', name: 'Kazakhstan' },
    { id: 'ke', name: 'Kenya' },
    { id: 'ki', name: 'Kiribati' },
    { id: 'kw', name: 'Kuwait' },
    { id: 'kg', name: 'Kyrgyzstan' },
    { id: 'la', name: 'Laos' },
    { id: 'lv', name: 'Latvia' },
    { id: 'lb', name: 'Lebanon' },
    { id: 'ls', name: 'Lesotho' },
    { id: 'lr', name: 'Liberia' },
    { id: 'ly', name: 'Libya' },
    { id: 'li', name: 'Liechtenstein' },
    { id: 'lt', name: 'Lithuania' },
    { id: 'lu', name: 'Luxembourg' },
    { id: 'mo', name: 'Macao SAR China' },
    { id: 'mg', name: 'Madagascar' },
    { id: 'mw', name: 'Malawi' },
    { id: 'my', name: 'Malaysia' },
    { id: 'mv', name: 'Maldives' },
    { id: 'ml', name: 'Mali' },
    { id: 'mt', name: 'Malta' },
    { id: 'mh', name: 'Marshall Islands' },
    { id: 'mq', name: 'Martinique' },
    { id: 'mr', name: 'Mauritania' },
    { id: 'mu', name: 'Mauritius' },
    { id: 'yt', name: 'Mayotte' },
    { id: 'mx', name: 'Mexico' },
    { id: 'fm', name: 'Micronesia' },
    { id: 'md', name: 'Moldova' },
    { id: 'mc', name: 'Monaco' },
    { id: 'mn', name: 'Mongolia' },
    { id: 'me', name: 'Montenegro' },
    { id: 'ms', name: 'Montserrat' },
    { id: 'ma', name: 'Morocco' },
    { id: 'mz', name: 'Mozambique' },
    { id: 'mm', name: 'Myanmar (Burma)' },
    { id: 'na', name: 'Namibia' },
    { id: 'nr', name: 'Nauru' },
    { id: 'np', name: 'Nepal' },
    { id: 'nl', name: 'Netherlands' },
    { id: 'nc', name: 'New Caledonia' },
    { id: 'nz', name: 'New Zealand' },
    { id: 'ni', name: 'Nicaragua' },
    { id: 'ne', name: 'Niger' },
    { id: 'ng', name: 'Nigeria' },
    { id: 'nu', name: 'Niue' },
    { id: 'nf', name: 'Norfolk Island' },
    { id: 'kp', name: 'North Korea' },
    { id: 'mk', name: 'North Macedonia' },
    { id: 'mp', name: 'Northern Mariana Islands' },
    { id: 'no', name: 'Norway' },
    { id: 'om', name: 'Oman' },
    { id: 'pk', name: 'Pakistan' },
    { id: 'pw', name: 'Palau' },
    { id: 'ps', name: 'Palestinian Territories' },
    { id: 'pa', name: 'Panama' },
    { id: 'pg', name: 'Papua New Guinea' },
    { id: 'py', name: 'Paraguay' },
    { id: 'pe', name: 'Peru' },
    { id: 'ph', name: 'Philippines' },
    { id: 'pn', name: 'Pitcairn Islands' },
    { id: 'pl', name: 'Poland' },
    { id: 'pt', name: 'Portugal' },
    { id: 'pr', name: 'Puerto Rico' },
    { id: 'qa', name: 'Qatar' },
    { id: 're', name: 'Réunion' },
    { id: 'ro', name: 'Romania' },
    { id: 'rw', name: 'Rwanda' },
    { id: 'ws', name: 'Samoa' },
    { id: 'sm', name: 'San Marino' },
    { id: 'st', name: 'São Tomé & Príncipe' },
    { id: 'sa', name: 'Saudi Arabia' },
    { id: 'sn', name: 'Senegal' },
    { id: 'rs', name: 'Serbia' },
    { id: 'sc', name: 'Seychelles' },
    { id: 'sl', name: 'Sierra Leone' },
    { id: 'sg', name: 'Singapore' },
    { id: 'sx', name: 'Sint Maarten' },
    { id: 'sk', name: 'Slovakia' },
    { id: 'si', name: 'Slovenia' },
    { id: 'sb', name: 'Solomon Islands' },
    { id: 'so', name: 'Somalia' },
    { id: 'za', name: 'South Africa' },
    { id: 'gs', name: 'South Georgia & South Sandwich Islands' },
    { id: 'ss', name: 'South Sudan' },
    { id: 'lk', name: 'Sri Lanka' },
    { id: 'bl', name: 'St. Barthélemy' },
    { id: 'sh', name: 'St. Helena' },
    { id: 'kn', name: 'St. Kitts & Nevis' },
    { id: 'lc', name: 'St. Lucia' },
    { id: 'mf', name: 'St. Martin' },
    { id: 'pm', name: 'St. Pierre & Miquelon' },
    { id: 'vc', name: 'St. Vincent & Grenadines' },
    { id: 'sd', name: 'Sudan' },
    { id: 'sr', name: 'Suriname' },
    { id: 'sj', name: 'Svalbard & Jan Mayen' },
    { id: 'se', name: 'Sweden' },
    { id: 'ch', name: 'Switzerland' },
    { id: 'sy', name: 'Syria' },
    { id: 'tw', name: 'Taiwan' },
    { id: 'tj', name: 'Tajikistan' },
    { id: 'tz', name: 'Tanzania' },
    { id: 'tl', name: 'Timor-Leste' },
    { id: 'tg', name: 'Togo' },
    { id: 'tk', name: 'Tokelau' },
    { id: 'to', name: 'Tonga' },
    { id: 'tt', name: 'Trinidad & Tobago' },
    { id: 'tn', name: 'Tunisia' },
    { id: 'tr', name: 'Türkiye' },
    { id: 'tm', name: 'Turkmenistan' },
    { id: 'tc', name: 'Turks & Caicos Islands' },
    { id: 'tv', name: 'Tuvalu' },
    { id: 'um', name: 'U.S. Outlying Islands' },
    { id: 'vi', name: 'U.S. Virgin Islands' },
    { id: 'ug', name: 'Uganda' },
    { id: 'ua', name: 'Ukraine' },
    { id: 'ae', name: 'United Arab Emirates' },
    { id: 'uy', name: 'Uruguay' },
    { id: 'uz', name: 'Uzbekistan' },
    { id: 'vu', name: 'Vanuatu' },
    { id: 'va', name: 'Vatican City' },
    { id: 've', name: 'Venezuela' },
    { id: 'vn', name: 'Vietnam' },
    { id: 'wf', name: 'Wallis & Futuna' },
    { id: 'eh', name: 'Western Sahara' },
    { id: 'ye', name: 'Yemen' },
    { id: 'zm', name: 'Zambia' },
    { id: 'zw', name: 'Zimbabwe' },
    { id: 'other', name: 'Other' }
  ],
  nationality_require_title: 'Profile Setup Required',
  nationality_require_content: 'Please set your nationality in the Profile page first, so we can recommend the most familiar hometown recipes for you.',
  nationality_require_confirm: 'Go to Setup',
  nationality_require_cancel: 'Cancel',
  tab_familiar_recipe: '🍴 Familiar Taste',
  tab_local_recipe: '📍 Try Local Style',

   // Errors
  err_analyze_failed: 'Failed to analyze, please retry',
  err_timeout: 'Request timeout, please retry',
  err_network: 'Network error, please retry',
  err_model: 'Model service error, please retry',
  err_file_read: 'Failed to read image, please retry',
  err_cloud_func: 'Cloud function error',

  // Result Page
  page_title_result: 'Analysis',
  res_freshness: 'Freshness',
  res_taste: 'Taste:',
  res_texture: 'Texture:',
  res_similar: 'Similar:',
  res_freshness_title: 'Freshness Check',
  res_clue_title: 'Indicators',
  res_recipes_title: 'Recommended Recipes',
  res_recipes: 'Recommended',
  res_etc: ' etc.',
  res_generate_list: 'Add Ingred. to List',
  res_view_recipe: 'View Recipe',
  res_generate_guide: 'Never miss an item',
  res_retake: 'Retake',
  res_save_success: 'Saved successfully',
  res_save_failed: 'Failed to save',
  res_disclaimer: '* AI analysis is for reference only, not a basis for food safety. Please rely on actual conditions.',
  res_incomplete: 'Incomplete result, please retake from another angle',
  res_back_home: 'Back Home',
  res_load_failed: 'Failed to load result',
  res_no_main_ingredient: 'Main ingredient not recognized',
  res_add_list_success: 'Added to list',
  res_add_list_failed: 'Failed to add',
  res_modal_title: 'Added to Today\'s List',
  res_modal_desc: 'Ingredients successfully added, do you want to view the list?',
  res_modal_back: 'Back',
  res_modal_continue: 'Scan Next',
  res_modal_view_list: 'View List',
  res_adding_to_list: 'Adding...',
  loading_familiar: 'Finding authentic recipes...',
  loading_local: 'Finding local specials...',
  res_analyzing: 'AI is analyzing ingredients...',
  loading_phrases_vision: [
    'Scanning ingredient textures...',
    'Analyzing freshness features...',
    'Matching global ingredient database...',
    'Generating ingredient profile...',
    'Almost there, please wait...'
  ],
  btn_search_tutorial: 'Search on YouTube',
  btn_search_tutorial_xcf: 'Search on Food.com',
  tutorial_sheet_title: 'YouTube Video Tutorials',
  tutorial_sheet_title_xcf: 'Food.com Recipes',
  tutorial_platform_xcf: 'Food.com',
  tutorial_link_xcf: 'Copy Web Link',
  tutorial_copy: 'Copy Video Link',
  tutorial_open: 'Tap to view',
  tutorial_copy_success: 'Link copied, please open in browser',
  tutorial_copy_fail: 'Failed to copy, please retry',
  tutorial_empty: 'No results found',

  // Recipe Page
  recipe_title_default: 'Recipe Details',
  recipe_add_to_list: 'Add to Shopping List',
  recipe_delete_ingredient: 'Delete Ingredient',
  recipe_confirm_delete: 'Are you sure to delete?',
  recipe_no_ingredient: 'No ingredients to add',
  recipe_adding: 'Adding...',
  recipe_added: 'Added to current list',
  recipe_add_failed: 'Failed to add',
  recipe_saving: 'Saving...',
  recipe_saved_already: 'Recipe already saved',
  recipe_saved_success: 'Saved to favorite recipes',
  recipe_save_failed: 'Failed to save',

  // List Page
  list_tab_planning: 'By Recipe',
  list_tab_execution: 'By Category',
  list_delete: 'Delete',
  list_add_recipe: 'Add Recipe / Dish',
  list_merge_prefix: 'Merge to ',
  list_merge_suffix: '?',
  list_add_all: 'Add All to New List',
  list_add_to_new: 'Add to New List',
  btn_finish_purchase: 'Finish Purchasing',
  title_finish_purchase: 'Finish Purchasing',
  content_finish_purchase: 'Are you sure you want to finish purchasing? This will clear the current list.',
  confirm_finish: 'Finish',
  cancel: 'Cancel',
  saving: 'Saving...',
  purchase_finished: 'Purchasing Finished',
  save_failed: 'Save Failed',
  list_empty_title: 'List is empty',
  list_empty_desc: 'Scan ingredients or add manually!',
  list_title: 'Shopping List',
  list_subtitle: "What you'll need",
  list_hint: 'Tick off as you go',
  list_item_freshness: 'Freshness',
  list_item_taste: 'Taste',
  list_item_texture: 'Texture',
  list_item_recipes: 'Recipes',
  list_share: 'Share',
  list_back_home: 'Back Home',
  list_clear: 'Clear History',
  err_cloud_save: 'Please enable cloud service to save records',
  list_canceling: 'Canceling...',
  list_cancel_success: 'Canceled saving',
  list_cancel_fail: 'Cancel failed, please retry',
  list_saving: 'Saving...',
  list_save_success: 'Saved to history',
  list_save_fail: 'Save failed, please retry',
  list_share_title: 'I am making 【{recipe}】, check out what to buy!',
  list_share_desc: 'Needs: ',
  list_add_placeholder: 'Add new item...',
  list_add_btn: 'Add',
  list_clear_title: 'Clear History',
  list_clear_confirm: 'Are you sure to clear all history? This cannot be undone.',
  list_clearing: 'Clearing...',
  list_clear_success: 'Cleared',
  list_clear_fail: 'Clear failed',

  // List Page Categories
  cat_seafood_meat_eggs: "Seafood, Meat & Eggs",
  cat_fresh_produce: "Fresh Produce",
  cat_grains_oils_condiments: "Grains, Oils & Condiments",
  cat_others: "Others",

  // My Page
  my_tab_collection: 'Ingredients\nStamp',
  my_tab_planning: 'Favorite\nRecipes',
  my_tab_execution: 'Shopping\nLists',
  my_select_all: 'Select All',
  my_unselect_all: 'Unselect All',
  my_delete_selected: 'Delete Selected',
  my_edit: 'Edit',
  my_title: 'My Kitchen',
  my_account_settings_tip: 'Tap to enter account settings',
  status_in_progress: 'In Progress',
  my_set_nickname: 'Tap to set nickname',
  my_input_nickname: 'Enter Nickname',
  my_login_tip: 'Click avatar and nickname above to login',
  my_history_title: 'Recent Scans',
  my_cloud_tip: 'Enable cloud service to save history',
  my_tap_to_retry: '(Tap to retry)',
  my_local_mode: 'Current is local experience mode',
  my_network_error: 'Network error',
  my_network_retry: 'Please check network and retry',
  my_empty_collection_title: 'No records found',
  my_empty_collection_desc: 'Try scanning an ingredient!',
  my_empty_planning_title: 'No recipes saved',
  my_empty_planning_desc: 'Scan ingredients to discover recipes!',
  my_empty_execution_title: 'No shopping lists',
  my_empty_execution_desc: 'Generate lists to never miss an item!',
  my_clear_btn: 'Clear History',
  my_err_cloud_user: 'Enable cloud service to save personal info',
  my_uploading_avatar: 'Uploading avatar...',
  my_upload_avatar_success: 'Avatar uploaded',
  my_upload_avatar_fail: 'Upload failed, please retry',
  my_saving_nickname: 'Saving...',
  my_save_nickname_success: 'Saved successfully',
  my_save_nickname_fail: 'Save failed, please retry',
  my_clear_title: 'Clear History',
  my_clear_confirm: 'Are you sure to clear all history? This cannot be undone.',
  my_clearing: 'Clearing...',
  my_clear_success: 'Cleared',
  my_clear_fail: 'Clear failed',
  my_empty: 'No records found, try scanning one!',
  my_load_more: 'Load More',
  my_no_more: 'No more records',
  my_delete: 'Delete',
  my_delete_confirm: 'Are you sure to delete this record?',
  my_delete_success: 'Deleted',
  my_delete_fail: 'Failed to delete',
  my_cancel: 'Cancel',
  my_confirm: 'Confirm',
  my_prev_page: 'Prev',
  my_next_page: 'Next',
  my_language: 'Language / 语言',
  my_feedback: 'Feedback & Contact',
  my_shopping_list: 'Shopping List',
  my_shopping_list_title: 'Shopping List on {mm}/{dd} {timePrefix}',
  my_time_morning: 'Morning',
  my_time_noon: 'Noon',
  my_time_evening: 'Evening',
  my_full_purchase: 'Full Shopping List',
  my_initial_bill: 'L',
  my_ingredients_count: 'Contains {count} ingredients',
  my_initial_recipe: 'R',

  // Feedback Page
  feedback_title: 'Feedback',
  feedback_greeting: "Hi, I'm Max, the developer of Mercadista. The product is still growing, please let me know your suggestions, issues or new feature ideas without hesitation!",
  feedback_placeholder: 'Please enter your questions or suggestions...',
  feedback_contact_label: 'Your Contact (Optional)',
  feedback_contact_placeholder: 'WeChat/Phone/Email, so we can reply',
  feedback_submit: 'Submit Feedback',
  feedback_author_title: 'Contact Developer',
  feedback_author_email: 'Email: ',
  feedback_author_linkedin: 'LinkedIn: ',
  feedback_copy: 'Copy',
  feedback_copied: 'Copied',
  feedback_submit_success: 'Thank you for your feedback!',
  feedback_submit_fail: 'Submit failed, please retry',
  feedback_empty_content: 'Please enter feedback content',
  feedback_submitting: 'Submitting...',
  feedback_upload_image: 'Upload Image ({{count}}/3)',
  feedback_upload_limit: 'You can upload up to 3 images',
  feedback_upload_failed: 'Image upload failed, please retry',

  lang_system: 'Auto (System)',
  lang_zh: '简体中文',
  lang_en: 'English',

  // Dynamically added translations
  err_load_failed: 'Failed to load',
  err_add_failed: 'Failed to add',
  list_all_added: 'All ingredients added to list',
  index_swipe_hint: 'Please swipe left or right',
  index_input_empty: 'Please enter ingredients',
  index_voice_empty: 'Failed to recognize voice',
  index_voice_no_ingredient: 'No ingredients recognized',
  index_record_failed: 'Recording failed: ',
  index_add_success: 'Added',
  list_edit_hint: 'Please switch to "By Recipe" to edit or delete',
  list_saved: 'Saved',
  list_recipe_exists: 'Recipe already exists',
  list_delete_ingredient: 'Delete Ingredient',
  list_delete_recipe: 'Delete Recipe',
  list_merge_hint: 'Smart Merge',
  list_confirm_delete: 'Are you sure to delete?',
  my_no_selection: 'No items selected',
  my_deleted: 'Deleted',
  my_delete_failed: 'Failed to delete',
  my_rename_unsupported: 'Recipe renaming not supported',
  my_modify_success: 'Modified successfully',
  my_modify_failed: 'Failed to modify',
  my_wx_version_low: 'WeChat version too low',
  my_deleting: 'Deleting...',
  my_batch_delete: 'Batch Delete',
  my_clear_records: 'Clear Records',
  onboarding_auth_hint: 'Permission Request',
  onboarding_auth_location_desc: 'Location permission needed for local recipes. Go to settings?',
  onboarding_auth_record_desc: 'Microphone permission needed for voice input. Go to settings?',

  // Others
  loading: 'Loading...',
  success: 'Success',
  fail: 'Failed'
};