module.exports = {
  // Global
  app_name: 'Mercadista',
  app_slogan: 'Elevate Your Everyday Market Finds',
  lang_switch: '中',
  tab_home: 'Home',
  tab_my: 'Profile',
  
  // Index Page
  camera_title: 'Snap to Identify',
   camera_desc: 'Identify · Check Freshness · Get Recipes',
   album_entry: 'Album',
   analyzing_title: 'Analyzing Ingredient...',
   analyzing_hint: 'Dazzled by the choices! Give me 15-30s to take a closer look...',
   
  // Nationality and Culture Experience
  nationality_title: 'Nationality',
  nationality_list: [
    { id: 'cn', name: 'China' },
    { id: 'us', name: 'United States' },
    { id: 'gb', name: 'United Kingdom' },
    { id: 'jp', name: 'Japan' },
    { id: 'kr', name: 'South Korea' },
    { id: 'fr', name: 'France' },
    { id: 'de', name: 'Germany' },
    { id: 'it', name: 'Italy' },
    { id: 'es', name: 'Spain' },
    { id: 'ru', name: 'Russia' },
    { id: 'th', name: 'Thailand' },
    { id: 'in', name: 'India' },
    { id: 'af', name: 'Afghanistan' },
    { id: 'ax', name: 'Åland Islands' },
    { id: 'al', name: 'Albania' },
    { id: 'dz', name: 'Algeria' },
    { id: 'as', name: 'American Samoa' },
    { id: 'ad', name: 'Andorra' },
    { id: 'ao', name: 'Angola' },
    { id: 'ai', name: 'Anguilla' },
    { id: 'aq', name: 'Antarctica' },
    { id: 'ag', name: 'Antigua & Barbuda' },
    { id: 'ar', name: 'Argentina' },
    { id: 'am', name: 'Armenia' },
    { id: 'aw', name: 'Aruba' },
    { id: 'au', name: 'Australia' },
    { id: 'at', name: 'Austria' },
    { id: 'az', name: 'Azerbaijan' },
    { id: 'bs', name: 'Bahamas' },
    { id: 'bh', name: 'Bahrain' },
    { id: 'bd', name: 'Bangladesh' },
    { id: 'bb', name: 'Barbados' },
    { id: 'by', name: 'Belarus' },
    { id: 'be', name: 'Belgium' },
    { id: 'bz', name: 'Belize' },
    { id: 'bj', name: 'Benin' },
    { id: 'bm', name: 'Bermuda' },
    { id: 'bt', name: 'Bhutan' },
    { id: 'bo', name: 'Bolivia' },
    { id: 'ba', name: 'Bosnia & Herzegovina' },
    { id: 'bw', name: 'Botswana' },
    { id: 'bv', name: 'Bouvet Island' },
    { id: 'br', name: 'Brazil' },
    { id: 'io', name: 'British Indian Ocean Territory' },
    { id: 'vg', name: 'British Virgin Islands' },
    { id: 'bn', name: 'Brunei' },
    { id: 'bg', name: 'Bulgaria' },
    { id: 'bf', name: 'Burkina Faso' },
    { id: 'bi', name: 'Burundi' },
    { id: 'kh', name: 'Cambodia' },
    { id: 'cm', name: 'Cameroon' },
    { id: 'ca', name: 'Canada' },
    { id: 'cv', name: 'Cape Verde' },
    { id: 'bq', name: 'Caribbean Netherlands' },
    { id: 'ky', name: 'Cayman Islands' },
    { id: 'cf', name: 'Central African Republic' },
    { id: 'td', name: 'Chad' },
    { id: 'cl', name: 'Chile' },
    { id: 'cx', name: 'Christmas Island' },
    { id: 'cc', name: 'Cocos (Keeling) Islands' },
    { id: 'co', name: 'Colombia' },
    { id: 'km', name: 'Comoros' },
    { id: 'cg', name: 'Congo - Brazzaville' },
    { id: 'cd', name: 'Congo - Kinshasa' },
    { id: 'ck', name: 'Cook Islands' },
    { id: 'cr', name: 'Costa Rica' },
    { id: 'ci', name: 'Côte d’Ivoire' },
    { id: 'hr', name: 'Croatia' },
    { id: 'cu', name: 'Cuba' },
    { id: 'cw', name: 'Curaçao' },
    { id: 'cy', name: 'Cyprus' },
    { id: 'cz', name: 'Czechia' },
    { id: 'dk', name: 'Denmark' },
    { id: 'dj', name: 'Djibouti' },
    { id: 'dm', name: 'Dominica' },
    { id: 'do', name: 'Dominican Republic' },
    { id: 'ec', name: 'Ecuador' },
    { id: 'eg', name: 'Egypt' },
    { id: 'sv', name: 'El Salvador' },
    { id: 'gq', name: 'Equatorial Guinea' },
    { id: 'er', name: 'Eritrea' },
    { id: 'ee', name: 'Estonia' },
    { id: 'sz', name: 'Eswatini' },
    { id: 'et', name: 'Ethiopia' },
    { id: 'fk', name: 'Falkland Islands' },
    { id: 'fo', name: 'Faroe Islands' },
    { id: 'fj', name: 'Fiji' },
    { id: 'fi', name: 'Finland' },
    { id: 'gf', name: 'French Guiana' },
    { id: 'pf', name: 'French Polynesia' },
    { id: 'tf', name: 'French Southern Territories' },
    { id: 'ga', name: 'Gabon' },
    { id: 'gm', name: 'Gambia' },
    { id: 'ge', name: 'Georgia' },
    { id: 'gh', name: 'Ghana' },
    { id: 'gi', name: 'Gibraltar' },
    { id: 'gr', name: 'Greece' },
    { id: 'gl', name: 'Greenland' },
    { id: 'gd', name: 'Grenada' },
    { id: 'gp', name: 'Guadeloupe' },
    { id: 'gu', name: 'Guam' },
    { id: 'gt', name: 'Guatemala' },
    { id: 'gg', name: 'Guernsey' },
    { id: 'gn', name: 'Guinea' },
    { id: 'gw', name: 'Guinea-Bissau' },
    { id: 'gy', name: 'Guyana' },
    { id: 'ht', name: 'Haiti' },
    { id: 'hm', name: 'Heard & McDonald Islands' },
    { id: 'hn', name: 'Honduras' },
    { id: 'hk', name: 'Hong Kong SAR China' },
    { id: 'hu', name: 'Hungary' },
    { id: 'is', name: 'Iceland' },
    { id: 'id', name: 'Indonesia' },
    { id: 'ir', name: 'Iran' },
    { id: 'iq', name: 'Iraq' },
    { id: 'ie', name: 'Ireland' },
    { id: 'im', name: 'Isle of Man' },
    { id: 'il', name: 'Israel' },
    { id: 'jm', name: 'Jamaica' },
    { id: 'je', name: 'Jersey' },
    { id: 'jo', name: 'Jordan' },
    { id: 'kz', name: 'Kazakhstan' },
    { id: 'ke', name: 'Kenya' },
    { id: 'ki', name: 'Kiribati' },
    { id: 'kw', name: 'Kuwait' },
    { id: 'kg', name: 'Kyrgyzstan' },
    { id: 'la', name: 'Laos' },
    { id: 'lv', name: 'Latvia' },
    { id: 'lb', name: 'Lebanon' },
    { id: 'ls', name: 'Lesotho' },
    { id: 'lr', name: 'Liberia' },
    { id: 'ly', name: 'Libya' },
    { id: 'li', name: 'Liechtenstein' },
    { id: 'lt', name: 'Lithuania' },
    { id: 'lu', name: 'Luxembourg' },
    { id: 'mo', name: 'Macao SAR China' },
    { id: 'mg', name: 'Madagascar' },
    { id: 'mw', name: 'Malawi' },
    { id: 'my', name: 'Malaysia' },
    { id: 'mv', name: 'Maldives' },
    { id: 'ml', name: 'Mali' },
    { id: 'mt', name: 'Malta' },
    { id: 'mh', name: 'Marshall Islands' },
    { id: 'mq', name: 'Martinique' },
    { id: 'mr', name: 'Mauritania' },
    { id: 'mu', name: 'Mauritius' },
    { id: 'yt', name: 'Mayotte' },
    { id: 'mx', name: 'Mexico' },
    { id: 'fm', name: 'Micronesia' },
    { id: 'md', name: 'Moldova' },
    { id: 'mc', name: 'Monaco' },
    { id: 'mn', name: 'Mongolia' },
    { id: 'me', name: 'Montenegro' },
    { id: 'ms', name: 'Montserrat' },
    { id: 'ma', name: 'Morocco' },
    { id: 'mz', name: 'Mozambique' },
    { id: 'mm', name: 'Myanmar (Burma)' },
    { id: 'na', name: 'Namibia' },
    { id: 'nr', name: 'Nauru' },
    { id: 'np', name: 'Nepal' },
    { id: 'nl', name: 'Netherlands' },
    { id: 'nc', name: 'New Caledonia' },
    { id: 'nz', name: 'New Zealand' },
    { id: 'ni', name: 'Nicaragua' },
    { id: 'ne', name: 'Niger' },
    { id: 'ng', name: 'Nigeria' },
    { id: 'nu', name: 'Niue' },
    { id: 'nf', name: 'Norfolk Island' },
    { id: 'kp', name: 'North Korea' },
    { id: 'mk', name: 'North Macedonia' },
    { id: 'mp', name: 'Northern Mariana Islands' },
    { id: 'no', name: 'Norway' },
    { id: 'om', name: 'Oman' },
    { id: 'pk', name: 'Pakistan' },
    { id: 'pw', name: 'Palau' },
    { id: 'ps', name: 'Palestinian Territories' },
    { id: 'pa', name: 'Panama' },
    { id: 'pg', name: 'Papua New Guinea' },
    { id: 'py', name: 'Paraguay' },
    { id: 'pe', name: 'Peru' },
    { id: 'ph', name: 'Philippines' },
    { id: 'pn', name: 'Pitcairn Islands' },
    { id: 'pl', name: 'Poland' },
    { id: 'pt', name: 'Portugal' },
    { id: 'pr', name: 'Puerto Rico' },
    { id: 'qa', name: 'Qatar' },
    { id: 're', name: 'Réunion' },
    { id: 'ro', name: 'Romania' },
    { id: 'rw', name: 'Rwanda' },
    { id: 'ws', name: 'Samoa' },
    { id: 'sm', name: 'San Marino' },
    { id: 'st', name: 'São Tomé & Príncipe' },
    { id: 'sa', name: 'Saudi Arabia' },
    { id: 'sn', name: 'Senegal' },
    { id: 'rs', name: 'Serbia' },
    { id: 'sc', name: 'Seychelles' },
    { id: 'sl', name: 'Sierra Leone' },
    { id: 'sg', name: 'Singapore' },
    { id: 'sx', name: 'Sint Maarten' },
    { id: 'sk', name: 'Slovakia' },
    { id: 'si', name: 'Slovenia' },
    { id: 'sb', name: 'Solomon Islands' },
    { id: 'so', name: 'Somalia' },
    { id: 'za', name: 'South Africa' },
    { id: 'gs', name: 'South Georgia & South Sandwich Islands' },
    { id: 'ss', name: 'South Sudan' },
    { id: 'lk', name: 'Sri Lanka' },
    { id: 'bl', name: 'St. Barthélemy' },
    { id: 'sh', name: 'St. Helena' },
    { id: 'kn', name: 'St. Kitts & Nevis' },
    { id: 'lc', name: 'St. Lucia' },
    { id: 'mf', name: 'St. Martin' },
    { id: 'pm', name: 'St. Pierre & Miquelon' },
    { id: 'vc', name: 'St. Vincent & Grenadines' },
    { id: 'sd', name: 'Sudan' },
    { id: 'sr', name: 'Suriname' },
    { id: 'sj', name: 'Svalbard & Jan Mayen' },
    { id: 'se', name: 'Sweden' },
    { id: 'ch', name: 'Switzerland' },
    { id: 'sy', name: 'Syria' },
    { id: 'tw', name: 'Taiwan' },
    { id: 'tj', name: 'Tajikistan' },
    { id: 'tz', name: 'Tanzania' },
    { id: 'tl', name: 'Timor-Leste' },
    { id: 'tg', name: 'Togo' },
    { id: 'tk', name: 'Tokelau' },
    { id: 'to', name: 'Tonga' },
    { id: 'tt', name: 'Trinidad & Tobago' },
    { id: 'tn', name: 'Tunisia' },
    { id: 'tr', name: 'Türkiye' },
    { id: 'tm', name: 'Turkmenistan' },
    { id: 'tc', name: 'Turks & Caicos Islands' },
    { id: 'tv', name: 'Tuvalu' },
    { id: 'um', name: 'U.S. Outlying Islands' },
    { id: 'vi', name: 'U.S. Virgin Islands' },
    { id: 'ug', name: 'Uganda' },
    { id: 'ua', name: 'Ukraine' },
    { id: 'ae', name: 'United Arab Emirates' },
    { id: 'uy', name: 'Uruguay' },
    { id: 'uz', name: 'Uzbekistan' },
    { id: 'vu', name: 'Vanuatu' },
    { id: 'va', name: 'Vatican City' },
    { id: 've', name: 'Venezuela' },
    { id: 'vn', name: 'Vietnam' },
    { id: 'wf', name: 'Wallis & Futuna' },
    { id: 'eh', name: 'Western Sahara' },
    { id: 'ye', name: 'Yemen' },
    { id: 'zm', name: 'Zambia' },
    { id: 'zw', name: 'Zimbabwe' },
    { id: 'other', name: 'Other' }
  ],
  nationality_require_title: 'Profile Setup Required',
  nationality_require_content: 'Please set your nationality in the Profile page first, so we can recommend the most familiar hometown recipes for you.',
  nationality_require_confirm: 'Go to Setup',
  nationality_require_cancel: 'Cancel',
  tab_familiar_recipe: '🍴 Familiar Taste',
  tab_local_recipe: '📍 Try Local Style',

   // Errors
  err_analyze_failed: 'Failed to analyze, please retry',
  err_timeout: 'Request timeout, please retry',
  err_network: 'Network error, please retry',
  err_model: 'Model service error, please retry',
  err_file_read: 'Failed to read image, please retry',
  err_cloud_func: 'Cloud function error',

  // Result Page
  page_title_result: 'Analysis',
  res_freshness: 'Freshness',
  res_taste: 'Taste:',
  res_texture: 'Texture:',
  res_similar: 'Similar:',
  res_freshness_title: 'Freshness Check',
  res_clue_title: 'Indicators',
  res_recipes_title: 'Recommended Recipes',
  res_recipes: 'Recipes',
  res_etc: ' etc.',
  res_generate_list: 'Shopping List',
  res_retake: 'Retake',
  res_save_success: 'Saved successfully',
  res_save_failed: 'Failed to save',
  res_disclaimer: '* AI analysis is for reference only, not a basis for food safety. Please rely on actual conditions.',
  res_incomplete: 'Incomplete result, please retake from another angle',
  res_back_home: 'Back Home',
  res_load_failed: 'Failed to load result',
  loading_familiar: 'Browsing recipes for you...',
  loading_local: 'Local recipes...',

  // List Page
  list_title: 'Shopping List',
  list_subtitle: "What you'll need",
  list_hint: 'Tick off as you go',
  list_item_freshness: 'Freshness',
  list_item_taste: 'Taste',
  list_item_texture: 'Texture',
  list_item_recipes: 'Recipes',
  list_share: 'Share',
  list_back_home: 'Back Home',
  list_clear: 'Clear History',
  err_cloud_save: 'Please enable cloud service to save records',
  list_canceling: 'Canceling...',
  list_cancel_success: 'Canceled saving',
  list_cancel_fail: 'Cancel failed, please retry',
  list_saving: 'Saving...',
  list_save_success: 'Saved to history',
  list_save_fail: 'Save failed, please retry',
  list_share_title: 'I am making 【{recipe}】, check out what to buy!',
  list_share_desc: 'Need: ',
  list_clear_title: 'Clear History',
  list_clear_confirm: 'Are you sure to clear all history? This cannot be undone.',
  list_clearing: 'Clearing...',
  list_clear_success: 'Cleared',
  list_clear_fail: 'Clear failed',

  // My Page
  my_title: 'Profile',
  my_set_nickname: 'Set Nickname',
  my_input_nickname: 'Enter Nickname',
  my_login_tip: 'Click avatar and nickname above to login',
  my_history_title: 'Recent Scans',
  my_cloud_tip: 'Enable cloud service to save history',
  my_local_mode: 'Current is local experience mode',
  my_network_error: 'Network error',
  my_network_retry: 'Please check network and retry',
  my_empty_title: 'No records found',
  my_empty_desc: 'Try scanning an ingredient!',
  my_clear_btn: 'Clear History',
  my_err_cloud_user: 'Enable cloud service to save personal info',
  my_uploading_avatar: 'Uploading avatar...',
  my_upload_avatar_success: 'Avatar uploaded',
  my_upload_avatar_fail: 'Upload failed, please retry',
  my_saving_nickname: 'Saving...',
  my_save_nickname_success: 'Saved successfully',
  my_save_nickname_fail: 'Save failed, please retry',
  my_clear_title: 'Clear History',
  my_clear_confirm: 'Are you sure to clear all history? This cannot be undone.',
  my_clearing: 'Clearing...',
  my_clear_success: 'Cleared',
  my_clear_fail: 'Clear failed',
  my_empty: 'No records found, try scanning one!',
  my_load_more: 'Load More',
  my_no_more: 'No more records',
  my_delete: 'Delete',
  my_delete_confirm: 'Are you sure to delete this record?',
  my_cancel: 'Cancel',
  my_confirm: 'Confirm',
  my_prev_page: 'Prev',
  my_next_page: 'Next',
  my_language: 'Language / 语言',
  my_feedback: 'Feedback & Contact',

  // Feedback Page
  feedback_title: 'Feedback',
  feedback_greeting: "Hi, I'm Max, the developer of Mercadista. The product is still growing, please let me know your suggestions, issues or new feature ideas without hesitation!",
  feedback_placeholder: 'Please enter your questions or suggestions...',
  feedback_contact_label: 'Your Contact (Optional)',
  feedback_contact_placeholder: 'WeChat/Phone/Email, so we can reply',
  feedback_submit: 'Submit Feedback',
  feedback_author_title: 'Contact Developer',
  feedback_author_email: 'Email: ',
  feedback_author_linkedin: 'LinkedIn: ',
  feedback_copy: 'Copy',
  feedback_copied: 'Copied',
  feedback_submit_success: 'Thank you for your feedback!',
  feedback_submit_fail: 'Submit failed, please retry',
  feedback_empty_content: 'Please enter feedback content',
  feedback_submitting: 'Submitting...',
  feedback_upload_image: 'Upload Image ({{count}}/3)',
  feedback_upload_limit: 'You can upload up to 3 images',
  feedback_upload_failed: 'Image upload failed, please retry',

  lang_system: 'Auto (System)',
  lang_zh: '简体中文',
  lang_en: 'English',

  // Others
  loading: 'Loading...',
  success: 'Success',
  fail: 'Failed'
};