module.exports = {
  // Global
  app_name: 'Mercadista',
  app_slogan: 'Elevate Your Everyday Market Finds',
  lang_switch: '中',
  tab_home: 'Home',
  tab_my: 'Profile',
  
  // Index Page
  camera_title: 'Snap to Identify',
   camera_desc: 'Identify · Check Freshness · Get Recipes',
   album_entry: 'Album',
   analyzing_title: 'Analyzing Ingredient...',
   analyzing_hint: 'Dazzled by the choices! Give me 15-30s to take a closer look...',
   
  // Nationality and Culture Experience
  nationality_title: 'Nationality',
  nationality_list: [
    { id: 'cn', name: 'China' },
    { id: 'fr', name: 'France' },
    { id: 'de', name: 'Germany' },
    { id: 'in', name: 'India' },
    { id: 'it', name: 'Italy' },
    { id: 'jp', name: 'Japan' },
    { id: 'ru', name: 'Russia' },
    { id: 'kr', name: 'South Korea' },
    { id: 'es', name: 'Spain' },
    { id: 'th', name: 'Thailand' },
    { id: 'gb', name: 'United Kingdom' },
    { id: 'us', name: 'United States' },
    { id: 'other', name: 'Other' }
  ],
  nationality_require_title: 'Profile Setup Required',
  nationality_require_content: 'Please set your nationality in the Profile page first, so we can recommend the most familiar hometown recipes for you.',
  nationality_require_confirm: 'Go to Setup',
  nationality_require_cancel: 'Cancel',
  tab_familiar_recipe: '🍴 Familiar Taste',
  tab_local_recipe: '📍 Try Local Style',

   // Errors
  err_analyze_failed: 'Failed to analyze, please retry',
  err_timeout: 'Request timeout, please retry',
  err_network: 'Network error, please retry',
  err_model: 'Model service error, please retry',
  err_file_read: 'Failed to read image, please retry',
  err_cloud_func: 'Cloud function error',

  // Result Page
  page_title_result: 'Analysis',
  res_freshness: 'Freshness',
  res_taste: 'Taste:',
  res_texture: 'Texture:',
  res_similar: 'Similar:',
  res_freshness_title: 'Freshness Check',
  res_clue_title: 'Indicators',
  res_recipes_title: 'Recommended Recipes',
  res_recipes: 'Recipes',
  res_etc: ' etc.',
  res_generate_list: 'Shopping List',
  res_retake: 'Retake',
  res_save_success: 'Saved successfully',
  res_save_failed: 'Failed to save',
  res_disclaimer: '* AI analysis is for reference only, not a basis for food safety. Please rely on actual conditions.',
  res_incomplete: 'Incomplete result, please retake from another angle',
  res_back_home: 'Back Home',
  res_load_failed: 'Failed to load result',
  loading_familiar: 'Browsing hometown recipes for you...',
  loading_local: 'Local recipes...',

  // List Page
  list_title: 'Shopping List',
  list_subtitle: "What you'll need",
  list_hint: 'Tick off as you go',
  list_item_freshness: 'Freshness',
  list_item_taste: 'Taste',
  list_item_texture: 'Texture',
  list_item_recipes: 'Recipes',
  list_share: 'Share',
  list_back_home: 'Back Home',
  list_clear: 'Clear History',
  err_cloud_save: 'Please enable cloud service to save records',
  list_canceling: 'Canceling...',
  list_cancel_success: 'Canceled saving',
  list_cancel_fail: 'Cancel failed, please retry',
  list_saving: 'Saving...',
  list_save_success: 'Saved to history',
  list_save_fail: 'Save failed, please retry',
  list_share_title: 'I am making 【{recipe}】, check out what to buy!',
  list_share_desc: 'Need: ',
  list_clear_title: 'Clear History',
  list_clear_confirm: 'Are you sure to clear all history? This cannot be undone.',
  list_clearing: 'Clearing...',
  list_clear_success: 'Cleared',
  list_clear_fail: 'Clear failed',

  // My Page
  my_title: 'Profile',
  my_set_nickname: 'Set Nickname',
  my_input_nickname: 'Enter Nickname',
  my_login_tip: 'Click avatar and nickname above to login',
  my_history_title: 'Recent Scans',
  my_cloud_tip: 'Enable cloud service to save history',
  my_local_mode: 'Current is local experience mode',
  my_network_error: 'Network error',
  my_network_retry: 'Please check network and retry',
  my_empty_title: 'No records found',
  my_empty_desc: 'Try scanning an ingredient!',
  my_clear_btn: 'Clear History',
  my_err_cloud_user: 'Enable cloud service to save personal info',
  my_uploading_avatar: 'Uploading avatar...',
  my_upload_avatar_success: 'Avatar uploaded',
  my_upload_avatar_fail: 'Upload failed, please retry',
  my_saving_nickname: 'Saving...',
  my_save_nickname_success: 'Saved successfully',
  my_save_nickname_fail: 'Save failed, please retry',
  my_clear_title: 'Clear History',
  my_clear_confirm: 'Are you sure to clear all history? This cannot be undone.',
  my_clearing: 'Clearing...',
  my_clear_success: 'Cleared',
  my_clear_fail: 'Clear failed',
  my_empty: 'No records found, try scanning one!',
  my_load_more: 'Load More',
  my_no_more: 'No more records',
  my_delete: 'Delete',
  my_delete_confirm: 'Are you sure to delete this record?',
  my_cancel: 'Cancel',
  my_confirm: 'Confirm',
  my_prev_page: 'Prev',
  my_next_page: 'Next',
  my_language: 'Language / 语言',
  lang_system: 'Auto (System)',
  lang_zh: '简体中文',
  lang_en: 'English',

  // Others
  loading: 'Loading...',
  success: 'Success',
  fail: 'Failed'
};