module.exports = {
  // 全局
  app_name: '知食公社',
  app_slogan: '集结懂吃的灵魂',
  lang_switch: 'EN',
  tab_home: '识菜',
  tab_my: '我的',
  
  // 首页
  camera_title: '拍照识别',
  camera_desc: '一眼识菜 · 一秒辨鲜 · 一键成菜',
  album_entry: '相册导入',
  analyzing_title: '正在分析食材特征...',
  analyzing_hint: '看花了眼啦！请给我15-30秒钟揉揉眼睛',
  
  // 国籍与文化体验
  nationality_title: '国籍 / Nationality',
  nationality_list: [
    { id: 'cn', name: '中国' },
    { id: 'de', name: '德国' },
    { id: 'ru', name: '俄罗斯' },
    { id: 'fr', name: '法国' },
    { id: 'kr', name: '韩国' },
    { id: 'us', name: '美国' },
    { id: 'jp', name: '日本' },
    { id: 'th', name: '泰国' },
    { id: 'es', name: '西班牙' },
    { id: 'it', name: '意大利' },
    { id: 'in', name: '印度' },
    { id: 'gb', name: '英国' },
    { id: 'other', name: '其他' }
  ],
  nationality_require_title: '需要完善信息',
  nationality_require_content: '请先在“我的”页面设置您的国籍，以便为您推荐最符合口味的家乡做法。',
  nationality_require_confirm: '去设置',
  nationality_require_cancel: '取消',
  tab_familiar_recipe: '🍴 熟悉的滋味',
  tab_local_recipe: '📍 试试当地做法',

  // 错误提示
  err_analyze_failed: '识别失败，请重试',
  err_timeout: '请求超时，请重试',
  err_network: '网络错误，请重试',
  err_model: '模型服务异常，请重试',
  err_file_read: '读取图片失败，请重试',
  err_cloud_func: '云函数调用失败',

  // 结果页
  page_title_result: '识别结果',
  res_freshness: '鲜度判定',
  res_taste: '味道：',
  res_texture: '口感：',
  res_similar: '类似食材：',
  res_freshness_title: '鲜度判定',
  res_clue_title: '判断依据',
  res_recipes_title: '推荐做法',
  res_recipes: '推荐做法',
  res_etc: ' 等',
  res_generate_list: '生成买菜清单',
  res_retake: '重新拍摄',
  res_save_success: '保存成功',
  res_save_failed: '保存失败',
  res_disclaimer: '* AI识别结果仅供参考，不作为食品安全判断依据，请以实际情况为准。',
  res_incomplete: '食材特征未完全识别，请换个角度重拍',
  res_back_home: '返回首页',
  res_load_failed: '加载识别结果失败',
  loading_familiar: '正在为您翻阅家乡菜谱...',
  loading_local: '探索当地做法...',

  // 列表页 (采购单)
  list_title: '采购单',
  list_subtitle: '需要准备以下佐料',
  list_hint: '买一样，勾选一样',
  list_item_freshness: '鲜度',
  list_item_taste: '口感',
  list_item_texture: '质地',
  list_item_recipes: '推荐做法',
  list_share: '分享',
  list_back_home: '返回首页',
  list_clear: '清除历史记录',
  err_cloud_save: '请开启云服务以保存记录',
  list_canceling: '取消中...',
  list_cancel_success: '已取消保存',
  list_cancel_fail: '取消失败，请重试',
  list_saving: '保存中...',
  list_save_success: '已保存至历史记录',
  list_save_fail: '保存失败，请重试',
  list_share_title: '今晚准备做【{recipe}】，快来看看需要买什么！',
  list_share_desc: '需要：',
  list_clear_title: '清除历史记录',
  list_clear_confirm: '确定清除所有历史记录吗？此操作不可恢复。',
  list_clearing: '清除中...',
  list_clear_success: '已清除',
  list_clear_fail: '清除失败',

  // 我的页 (历史记录)
  my_title: '我的记录',
  my_set_nickname: '点击设置昵称',
  my_input_nickname: '请输入昵称',
  my_login_tip: '点击上方头像和昵称即可登录',
  my_history_title: '历史记录',
  my_cloud_tip: '请开启云服务以保存历史',
  my_local_mode: '当前为本地体验模式',
  my_network_error: '网络好像开小差了',
  my_network_retry: '请检查网络后重试',
  my_empty_title: '暂无识别记录',
  my_empty_desc: '去拍个食材试试看吧～',
  my_clear_btn: '清除历史记录',
  my_err_cloud_user: '请开启云服务以保存个人信息',
  my_uploading_avatar: '上传头像中...',
  my_upload_avatar_success: '头像上传成功',
  my_upload_avatar_fail: '上传失败，请重试',
  my_saving_nickname: '保存中...',
  my_save_nickname_success: '保存成功',
  my_save_nickname_fail: '保存失败，请重试',
  my_clear_title: '清除历史记录',
  my_clear_confirm: '确定清除所有历史记录吗？此操作不可恢复。',
  my_clearing: '清除中...',
  my_clear_success: '已清除',
  my_clear_fail: '清除失败',
  my_empty: '暂无识别记录，快去拍一张吧',
  my_load_more: '加载更多',
  my_no_more: '没有更多记录了',
  my_delete: '删除',
  my_delete_confirm: '确定删除这条记录吗？',
  my_cancel: '取消',
  my_confirm: '确定',
  my_prev_page: '上一页',
  my_next_page: '下一页',
  my_language: '语言 / Language',
  lang_system: '跟随系统（默认）',
  lang_zh: '简体中文',
  lang_en: 'English',

  // 其他
  loading: '加载中...',
  success: '成功',
  fail: '失败'
};