module.exports = {
  // 全局
  app_name: '知食角',
  app_slogan: '聚集全球爱动手的吃货',
  lang_switch: 'EN',
  tab_home: '首页',
  tab_list: '清单',
  tab_my: '我的',
  page_title_list: '采购清单',
  
  list_merge_confirm_content: 'AI发现 [{source}] 和 [{target}] 可能是同类计划，合并为 [{target}] 还是 [保持分开]？',
  list_merge_confirm_yes: '合并',
  list_merge_confirm_no: '保持分开',
  list_add_recipe_title: '添加菜谱/菜品',
  list_add_recipe_placeholder: '请输入名称 (如: 辣椒炒肉)',
  list_edit_ingredient_title: '编辑食材',
  list_edit_ingredient_placeholder: '请输入新食材名称',
  list_delete_recipe_confirm: '确认删除【{recipe}】下的所有食材吗？',
  list_independent_ingredients: '独立食材',
  list_other_ingredients: '其他',
  list_direct_add: '直接添加',
  my_batch_delete_confirm: '确定要删除选中的 {count} 项吗？',
  my_rename_title: '重命名',
  my_rename_placeholder: '请输入新名称',
  my_clear_tab_execution: '所有账单',
  my_clear_tab_planning: '所有菜谱',
  my_clear_tab_collection: '所有集邮',
  my_clear_tab_confirm: '确定要清空{tabName}吗？清空后无法恢复。',
  // 首页
  camera_title: '拍照识别',
  camera_desc: '一眼识菜 · 一秒辨鲜 · 一键成菜',
  album_entry: '相册导入',
  transition_identify: '鉴食材',
  transition_list: '列清单',
  list_progress_title: '今日采购清单',
  list_progress_desc: '{bought} / {total} 项已购',
  swipe_guide: '扫货不遗漏',
  fab_note: '记一笔',
  analyzing_title: '正在分析食材特征...',
  analyzing_hint: '看花了眼啦！请给我15-30秒钟揉揉眼睛',
  index_stop_record: '点击停止录音',
  index_generate_list: '生成采购单',
  index_ai_processing: 'AI大厨正在为您处理，请稍候',
  index_quick_record: '📝 快速记录食材',
  index_record_placeholder: '可以直接填写菜名（如：西红柿炒鸡蛋）\n或者直接写食材（如：3个西红柿、半斤牛肉）...',
  index_generate_btn: '生成清单',
  
  // 引导授权页
  onboarding_title: '欢迎使用知食角',
  onboarding_subtitle: '为了给您提供更智能、更个性化的服务，我们需要获取以下信息与权限：',
  onboarding_profile_title: '基础资料',
  onboarding_profile_desc: '用于个性化展示您的个人主页。',
  onboarding_culture_title: '饮食文化',
  onboarding_culture_desc: '根据您的背景，为您推荐更符合口味的菜谱。',
  onboarding_location_title: '位置权限',
  onboarding_location_desc: '获取您的模糊位置，以推荐当地特色菜谱。',
  onboarding_record_title: '麦克风权限',
  onboarding_record_desc: '支持通过语音快捷录入食材。',
  onboarding_btn_auth: '授权',
  onboarding_btn_authed: '已授权',
  onboarding_btn_enter: '开启体验',
  onboarding_require_all: '请完善以上信息与权限',
  onboarding_input_nickname: '点击输入昵称',
  onboarding_select_nationality: '请选择您的国籍',
  onboarding_fuzzy_location: '模糊定位',
  onboarding_mic_record: '麦克风录音',
  onboarding_btn_save: '保存设置',

  // 国籍与文化体验
  nationality_title: '国籍 / Nationality',
  nationality_list: [
    { id: 'cn', name: '中国' },
    { id: 'us', name: '美国' },
    { id: 'gb', name: '英国' },
    { id: 'jp', name: '日本' },
    { id: 'kr', name: '韩国' },
    { id: 'fr', name: '法国' },
    { id: 'de', name: '德国' },
    { id: 'it', name: '意大利' },
    { id: 'es', name: '西班牙' },
    { id: 'ru', name: '俄罗斯' },
    { id: 'th', name: '泰国' },
    { id: 'in', name: '印度' },
    { id: 'af', name: '阿富汗' },
    { id: 'ax', name: '奥兰群岛' },
    { id: 'al', name: '阿尔巴尼亚' },
    { id: 'dz', name: '阿尔及利亚' },
    { id: 'as', name: '美属萨摩亚' },
    { id: 'ad', name: '安道尔' },
    { id: 'ao', name: '安哥拉' },
    { id: 'ai', name: '安圭拉' },
    { id: 'aq', name: '南极洲' },
    { id: 'ag', name: '安提瓜和巴布达' },
    { id: 'ar', name: '阿根廷' },
    { id: 'am', name: '亚美尼亚' },
    { id: 'aw', name: '阿鲁巴' },
    { id: 'au', name: '澳大利亚' },
    { id: 'at', name: '奥地利' },
    { id: 'az', name: '阿塞拜疆' },
    { id: 'bs', name: '巴哈马' },
    { id: 'bh', name: '巴林' },
    { id: 'bd', name: '孟加拉国' },
    { id: 'bb', name: '巴巴多斯' },
    { id: 'by', name: '白俄罗斯' },
    { id: 'be', name: '比利时' },
    { id: 'bz', name: '伯利兹' },
    { id: 'bj', name: '贝宁' },
    { id: 'bm', name: '百慕大' },
    { id: 'bt', name: '不丹' },
    { id: 'bo', name: '玻利维亚' },
    { id: 'ba', name: '波斯尼亚和黑塞哥维那' },
    { id: 'bw', name: '博茨瓦纳' },
    { id: 'bv', name: '布韦岛' },
    { id: 'br', name: '巴西' },
    { id: 'io', name: '英属印度洋领地' },
    { id: 'vg', name: '英属维尔京群岛' },
    { id: 'bn', name: '文莱' },
    { id: 'bg', name: '保加利亚' },
    { id: 'bf', name: '布基纳法索' },
    { id: 'bi', name: '布隆迪' },
    { id: 'kh', name: '柬埔寨' },
    { id: 'cm', name: '喀麦隆' },
    { id: 'ca', name: '加拿大' },
    { id: 'cv', name: '佛得角' },
    { id: 'bq', name: '荷属加勒比区' },
    { id: 'ky', name: '开曼群岛' },
    { id: 'cf', name: '中非共和国' },
    { id: 'td', name: '乍得' },
    { id: 'cl', name: '智利' },
    { id: 'cx', name: '圣诞岛' },
    { id: 'cc', name: '科科斯（基林）群岛' },
    { id: 'co', name: '哥伦比亚' },
    { id: 'km', name: '科摩罗' },
    { id: 'cg', name: '刚果（布）' },
    { id: 'cd', name: '刚果（金）' },
    { id: 'ck', name: '库克群岛' },
    { id: 'cr', name: '哥斯达黎加' },
    { id: 'ci', name: '科特迪瓦' },
    { id: 'hr', name: '克罗地亚' },
    { id: 'cu', name: '古巴' },
    { id: 'cw', name: '库拉索' },
    { id: 'cy', name: '塞浦路斯' },
    { id: 'cz', name: '捷克' },
    { id: 'dk', name: '丹麦' },
    { id: 'dj', name: '吉布提' },
    { id: 'dm', name: '多米尼克' },
    { id: 'do', name: '多米尼加共和国' },
    { id: 'ec', name: '厄瓜多尔' },
    { id: 'eg', name: '埃及' },
    { id: 'sv', name: '萨尔瓦多' },
    { id: 'gq', name: '赤道几内亚' },
    { id: 'er', name: '厄立特里亚' },
    { id: 'ee', name: '爱沙尼亚' },
    { id: 'sz', name: '斯威士兰' },
    { id: 'et', name: '埃塞俄比亚' },
    { id: 'fk', name: '福克兰群岛' },
    { id: 'fo', name: '法罗群岛' },
    { id: 'fj', name: '斐济' },
    { id: 'fi', name: '芬兰' },
    { id: 'gf', name: '法属圭亚那' },
    { id: 'pf', name: '法属波利尼西亚' },
    { id: 'tf', name: '法属南部领地' },
    { id: 'ga', name: '加蓬' },
    { id: 'gm', name: '冈比亚' },
    { id: 'ge', name: '格鲁吉亚' },
    { id: 'gh', name: '加纳' },
    { id: 'gi', name: '直布罗陀' },
    { id: 'gr', name: '希腊' },
    { id: 'gl', name: '格陵兰' },
    { id: 'gd', name: '格林纳达' },
    { id: 'gp', name: '瓜德罗普' },
    { id: 'gu', name: '关岛' },
    { id: 'gt', name: '危地马拉' },
    { id: 'gg', name: '根西岛' },
    { id: 'gn', name: '几内亚' },
    { id: 'gw', name: '几内亚比绍' },
    { id: 'gy', name: '圭亚那' },
    { id: 'ht', name: '海地' },
    { id: 'hm', name: '赫德岛和麦克唐纳群岛' },
    { id: 'hn', name: '洪都拉斯' },
    { id: 'hk', name: '中国香港特别行政区' },
    { id: 'hu', name: '匈牙利' },
    { id: 'is', name: '冰岛' },
    { id: 'id', name: '印度尼西亚' },
    { id: 'ir', name: '伊朗' },
    { id: 'iq', name: '伊拉克' },
    { id: 'ie', name: '爱尔兰' },
    { id: 'im', name: '马恩岛' },
    { id: 'il', name: '以色列' },
    { id: 'jm', name: '牙买加' },
    { id: 'je', name: '泽西岛' },
    { id: 'jo', name: '约旦' },
    { id: 'kz', name: '哈萨克斯坦' },
    { id: 'ke', name: '肯尼亚' },
    { id: 'ki', name: '基里巴斯' },
    { id: 'kw', name: '科威特' },
    { id: 'kg', name: '吉尔吉斯斯坦' },
    { id: 'la', name: '老挝' },
    { id: 'lv', name: '拉脱维亚' },
    { id: 'lb', name: '黎巴嫩' },
    { id: 'ls', name: '莱索托' },
    { id: 'lr', name: '利比里亚' },
    { id: 'ly', name: '利比亚' },
    { id: 'li', name: '列支敦士登' },
    { id: 'lt', name: '立陶宛' },
    { id: 'lu', name: '卢森堡' },
    { id: 'mo', name: '中国澳门特别行政区' },
    { id: 'mg', name: '马达加斯加' },
    { id: 'mw', name: '马拉维' },
    { id: 'my', name: '马来西亚' },
    { id: 'mv', name: '马尔代夫' },
    { id: 'ml', name: '马里' },
    { id: 'mt', name: '马耳他' },
    { id: 'mh', name: '马绍尔群岛' },
    { id: 'mq', name: '马提尼克' },
    { id: 'mr', name: '毛里塔尼亚' },
    { id: 'mu', name: '毛里求斯' },
    { id: 'yt', name: '马约特' },
    { id: 'mx', name: '墨西哥' },
    { id: 'fm', name: '密克罗尼西亚' },
    { id: 'md', name: '摩尔多瓦' },
    { id: 'mc', name: '摩纳哥' },
    { id: 'mn', name: '蒙古' },
    { id: 'me', name: '黑山' },
    { id: 'ms', name: '蒙特塞拉特' },
    { id: 'ma', name: '摩洛哥' },
    { id: 'mz', name: '莫桑比克' },
    { id: 'mm', name: '缅甸' },
    { id: 'na', name: '纳米比亚' },
    { id: 'nr', name: '瑙鲁' },
    { id: 'np', name: '尼泊尔' },
    { id: 'nl', name: '荷兰' },
    { id: 'nc', name: '新喀里多尼亚' },
    { id: 'nz', name: '新西兰' },
    { id: 'ni', name: '尼加拉瓜' },
    { id: 'ne', name: '尼日尔' },
    { id: 'ng', name: '尼日利亚' },
    { id: 'nu', name: '纽埃' },
    { id: 'nf', name: '诺福克岛' },
    { id: 'kp', name: '朝鲜' },
    { id: 'mk', name: '北马其顿' },
    { id: 'mp', name: '北马里亚纳群岛' },
    { id: 'no', name: '挪威' },
    { id: 'om', name: '阿曼' },
    { id: 'pk', name: '巴基斯坦' },
    { id: 'pw', name: '帕劳' },
    { id: 'ps', name: '巴勒斯坦领土' },
    { id: 'pa', name: '巴拿马' },
    { id: 'pg', name: '巴布亚新几内亚' },
    { id: 'py', name: '巴拉圭' },
    { id: 'pe', name: '秘鲁' },
    { id: 'ph', name: '菲律宾' },
    { id: 'pn', name: '皮特凯恩群岛' },
    { id: 'pl', name: '波兰' },
    { id: 'pt', name: '葡萄牙' },
    { id: 'pr', name: '波多黎各' },
    { id: 'qa', name: '卡塔尔' },
    { id: 're', name: '留尼汪' },
    { id: 'ro', name: '罗马尼亚' },
    { id: 'rw', name: '卢旺达' },
    { id: 'ws', name: '萨摩亚' },
    { id: 'sm', name: '圣马力诺' },
    { id: 'st', name: '圣多美和普林西比' },
    { id: 'sa', name: '沙特阿拉伯' },
    { id: 'sn', name: '塞内加尔' },
    { id: 'rs', name: '塞尔维亚' },
    { id: 'sc', name: '塞舌尔' },
    { id: 'sl', name: '塞拉利昂' },
    { id: 'sg', name: '新加坡' },
    { id: 'sx', name: '荷属圣马丁' },
    { id: 'sk', name: '斯洛伐克' },
    { id: 'si', name: '斯洛文尼亚' },
    { id: 'sb', name: '所罗门群岛' },
    { id: 'so', name: '索马里' },
    { id: 'za', name: '南非' },
    { id: 'gs', name: '南乔治亚和南桑威奇群岛' },
    { id: 'ss', name: '南苏丹' },
    { id: 'lk', name: '斯里兰卡' },
    { id: 'bl', name: '圣巴泰勒米' },
    { id: 'sh', name: '圣赫勒拿' },
    { id: 'kn', name: '圣基茨和尼维斯' },
    { id: 'lc', name: '圣卢西亚' },
    { id: 'mf', name: '法属圣马丁' },
    { id: 'pm', name: '圣皮埃尔和密克隆群岛' },
    { id: 'vc', name: '圣文森特和格林纳丁斯' },
    { id: 'sd', name: '苏丹' },
    { id: 'sr', name: '苏里南' },
    { id: 'sj', name: '斯瓦尔巴和扬马延' },
    { id: 'se', name: '瑞典' },
    { id: 'ch', name: '瑞士' },
    { id: 'sy', name: '叙利亚' },
    { id: 'tw', name: '台湾' },
    { id: 'tj', name: '塔吉克斯坦' },
    { id: 'tz', name: '坦桑尼亚' },
    { id: 'tl', name: '东帝汶' },
    { id: 'tg', name: '多哥' },
    { id: 'tk', name: '托克劳' },
    { id: 'to', name: '汤加' },
    { id: 'tt', name: '特立尼达和多巴哥' },
    { id: 'tn', name: '突尼斯' },
    { id: 'tr', name: '土耳其' },
    { id: 'tm', name: '土库曼斯坦' },
    { id: 'tc', name: '特克斯和凯科斯群岛' },
    { id: 'tv', name: '图瓦卢' },
    { id: 'um', name: '美国本土外小岛屿' },
    { id: 'vi', name: '美属维尔京群岛' },
    { id: 'ug', name: '乌干达' },
    { id: 'ua', name: '乌克兰' },
    { id: 'ae', name: '阿拉伯联合酋长国' },
    { id: 'uy', name: '乌拉圭' },
    { id: 'uz', name: '乌兹别克斯坦' },
    { id: 'vu', name: '瓦努阿图' },
    { id: 'va', name: '梵蒂冈' },
    { id: 've', name: '委内瑞拉' },
    { id: 'vn', name: '越南' },
    { id: 'wf', name: '瓦利斯和富图纳' },
    { id: 'eh', name: '西撒哈拉' },
    { id: 'ye', name: '也门' },
    { id: 'zm', name: '赞比亚' },
    { id: 'zw', name: '津巴布韦' },
    { id: 'other', name: '其他' }
  ],
  nationality_require_title: '需要完善信息',
  nationality_require_content: '请先在“我的”页面设置您的国籍，以便为您推荐最符合口味的家乡做法。',
  nationality_require_confirm: '去设置',
  nationality_require_cancel: '取消',
  tab_familiar_recipe: '🍴 熟悉的滋味',
  tab_local_recipe: '📍 试试当地做法',

  // 错误提示
  err_analyze_failed: '识别失败，请重试',
  err_timeout: '请求超时，请重试',
  err_network: '网络错误，请重试',
  err_model: '模型服务异常，请重试',
  err_file_read: '读取图片失败，请重试',
  err_cloud_func: '云函数调用失败',

  // 结果页
  page_title_result: '识别结果',
  res_freshness: '鲜度判定',
  res_taste: '味道：',
  res_texture: '口感：',
  res_similar: '相似食材：',
  res_adding_favorite: '正在收藏...',
  res_added_favorite: '已加入集邮册',
  res_removing_favorite: '正在移除...',
  res_removed_favorite: '已移除收藏',
  res_freshness_title: '鲜度判定',
  res_clue_title: '判断依据',
  res_recipes_title: '做法推荐',
  res_recipes: '推荐做法',
  res_etc: ' 等',
  res_generate_list: '将食材加入购物单',
  res_view_recipe: '查看食谱',
  res_generate_guide: '扫货不遗漏',
  res_retake: '重新拍摄',
  res_save_success: '保存成功',
  res_save_failed: '保存失败',
  res_disclaimer: '*分析结果由AI生成，仅供参考。如果识别有误，请重新尝试。',
  res_incomplete: '食材特征未完全识别，请换个角度重拍',
  res_back_home: '返回首页',
  res_load_failed: '加载识别结果失败',
  res_no_main_ingredient: '未识别到主食材',
  res_add_list_success: '已加入清单',
  res_add_list_failed: '加入失败',
  res_modal_title: '已加入今日采购清单',
  res_modal_desc: '食材已成功加入，是否前往查看？',
  res_modal_back: '返回',
  res_modal_continue: '继续识物',
  res_modal_view_list: '查看清单',
  res_adding_to_list: '正在加入...',
  loading_familiar: '正在为您定制地道做法...',
  loading_local: '正在寻找当地特色...',
  res_analyzing: 'AI 正在分析食材特征...',
  loading_phrases_vision: [
    'AI 正在扫描食材纹理...',
    '正在分析新鲜度特征...',
    '正在匹配全球食材库...',
    '正在生成食材档案...',
    '马上就好，稍等片刻...'
  ],
  btn_search_tutorial: '搜 B站 做法',
  btn_search_tutorial_xcf: '搜 下厨房 做法',
  tutorial_sheet_title: 'B站 推荐做法',
  tutorial_sheet_title_xcf: '下厨房 推荐做法',
  tutorial_platform_xcf: '下厨房',
  tutorial_link_xcf: '复制网页链接',
  tutorial_copy: '复制视频链接',
  tutorial_open: '点击前往查看',
  tutorial_copy_success: '链接已复制，请在浏览器中打开',
  tutorial_copy_fail: '复制失败，请重试',
  tutorial_empty: '暂未找到相关做法',

  // 食谱页
  recipe_title_default: '菜谱详情',
  recipe_add_to_list: '添加到采购清单',
  recipe_delete_ingredient: '删除食材',
  recipe_confirm_delete: '确认删除？',
  recipe_no_ingredient: '无食材可添加',
  recipe_adding: '添加中...',
  recipe_added: '已加入当前清单',
  recipe_add_failed: '添加失败',
  recipe_saving: '正在收藏...',
  recipe_saved_already: '已收藏过该食谱',
  recipe_saved_success: '已收藏至宝藏食谱',
  recipe_save_failed: '收藏失败',

  // 清单页分类
  cat_seafood_meat_eggs: "鱼鲜肉蛋",
  cat_fresh_produce: "生鲜蔬果",
  cat_grains_oils_condiments: "粮油配料",
  cat_others: "其他",

  // 列表页 (采购单)
  list_tab_planning: '逐道菜选购',
  list_tab_execution: '汇总选购',
  list_delete: '删除',
  list_add_recipe: '添加菜谱 / 菜品',
  list_merge_prefix: '合并到',
  list_merge_suffix: '?',
  list_add_all: '全部加入新清单',
  list_add_to_new: '加入新清单',
  btn_finish_purchase: '结束本次采购',
  title_finish_purchase: '结束采购',
  content_finish_purchase: '确认已买齐并结束本次采购吗？结束后将清空当前清单。',
  confirm_finish: '结束',
  cancel: '取消',
  saving: '保存中...',
  purchase_finished: '采购已结束',
  save_failed: '保存失败',
  list_empty_title: '当前清单为空',
  list_empty_desc: '去首页识物或记一笔吧～',
  list_title: '采购单',
  list_subtitle: '需要准备以下佐料',
  list_hint: '买一样，勾选一样',
  list_item_freshness: '鲜度',
  list_item_taste: '口感',
  list_item_texture: '质地',
  list_item_recipes: '推荐做法',
  list_share: '分享',
  list_back_home: '返回首页',
  list_clear: '清除历史记录',
  err_cloud_save: '请开启云服务以保存记录',
  list_canceling: '取消中...',
  list_cancel_success: '已取消保存',
  list_cancel_fail: '取消失败，请重试',
  list_saving: '保存中...',
  list_save_success: '已保存至历史记录',
  list_save_fail: '保存失败，请重试',
  list_share_title: '今晚准备做【{recipe}】，快来看看需要买什么！',
  list_share_desc: '需要：',
  list_add_placeholder: '添加新条目...',
  list_add_btn: '添加',
  list_clear_title: '清除历史记录',
  list_clear_confirm: '确定清除所有历史记录吗？此操作不可恢复。',
  list_clearing: '清除中...',
  list_clear_success: '已清除',
  list_clear_fail: '清除失败',

  // 我的页 (历史记录)
  my_tab_collection: '食材集邮册',
  my_tab_planning: '宝藏菜谱',
  my_tab_execution: '历史购物单',
  my_select_all: '全选',
  my_unselect_all: '取消全选',
  my_delete_selected: '删除选中',
  my_edit: '编辑',
  my_title: '我的厨房',
  my_account_settings_tip: '点击进入账号设置',
  status_in_progress: '进行中',
  my_set_nickname: '点击设置昵称',
  my_input_nickname: '请输入昵称',
  my_login_tip: '点击上方头像和昵称即可登录',
  my_history_title: '历史记录',
  my_cloud_tip: '请开启云服务以保存历史',
  my_tap_to_retry: '(点击重试)',
  my_local_mode: '当前为本地体验模式',
  my_network_error: '网络好像开小差了',
  my_network_retry: '请检查网络后重试',
  my_empty_collection_title: '暂无识别记录',
  my_empty_collection_desc: '去拍个食材试试看吧～',
  my_empty_planning_title: '暂无宝藏菜谱',
  my_empty_planning_desc: '识别食材，发现更多美味做法～',
  my_empty_execution_title: '暂无历史购物单',
  my_empty_execution_desc: '生成采购清单，买菜不遗漏～',
  my_clear_btn: '清除历史记录',
  my_err_cloud_user: '请开启云服务以保存个人信息',
  my_uploading_avatar: '上传头像中...',
  my_upload_avatar_success: '头像上传成功',
  my_upload_avatar_fail: '上传失败，请重试',
  my_saving_nickname: '保存中...',
  my_save_nickname_success: '保存成功',
  my_save_nickname_fail: '保存失败，请重试',
  my_clear_title: '清除历史记录',
  my_clear_confirm: '确定清除所有历史记录吗？此操作不可恢复。',
  my_clearing: '清除中...',
  my_clear_success: '已清除',
  my_clear_fail: '清除失败',
  my_empty: '暂无识别记录，快去拍一张吧',
  my_load_more: '加载更多',
  my_no_more: '没有更多记录了',
  my_delete: '删除',
  my_delete_confirm: '确定删除这条记录吗？',
  my_delete_success: '已删除',
  my_delete_fail: '删除失败',
  my_cancel: '取消',
  my_confirm: '确定',
  my_prev_page: '上一页',
  my_next_page: '下一页',
  my_language: '语言 / Language',
  my_feedback: '意见反馈与联系作者',

  // Feedback Page
  feedback_title: '意见反馈',
  feedback_greeting: '嗨，我是知食角的开发者Max。产品还在成长中，有什么吐槽或期待，请毫不客气地告诉我！',
  feedback_placeholder: '请输入您的问题、建议或想要的功能...',
  feedback_contact_label: '您的联系方式（选填）',
  feedback_contact_placeholder: '微信号/手机号/邮箱，方便我们回复您',
  feedback_submit: '提交反馈',
  feedback_author_title: '联系开发者',
  feedback_author_email: '邮箱：',
  feedback_author_linkedin: '领英：',
  feedback_copy: '复制',
  feedback_copied: '已复制',
  feedback_submit_success: '感谢您的反馈！',
  feedback_submit_fail: '提交失败，请重试',
  feedback_empty_content: '请先输入反馈内容',
  feedback_submitting: '提交中...',
  feedback_upload_image: '上传截图 ({{count}}/3)',
  feedback_upload_limit: '最多只能上传3张图片',
  feedback_upload_failed: '图片上传失败，请重试',

  lang_system: '跟随系统（默认）',
  lang_zh: '简体中文',
  lang_en: 'English',

  // 动态添加的翻译
  err_load_failed: '加载失败',
  err_add_failed: '添加失败',
  list_all_added: '全部食材已加入当前清单',
  index_swipe_hint: '请向左或向右滑动',
  index_input_empty: '请输入食材内容',
  index_voice_empty: '未能识别到语音内容',
  index_voice_no_ingredient: '未能识别到食材',
  index_record_failed: '录音失败: ',
  index_add_success: '添加成功',
  list_edit_hint: '如需修改或删除，请切换至“逐道菜选购”操作',
  list_saved: '已收藏',
  list_recipe_exists: '已存在该菜谱',
  list_delete_ingredient: '删除食材',
  list_delete_recipe: '删除整道菜',
  list_merge_hint: '智能合并提示',
  list_confirm_delete: '确认删除？',
  my_no_selection: '未选中任何项',
  my_deleted: '已删除',
  my_delete_failed: '删除失败',
  my_rename_unsupported: '菜谱不支持重命名',
  my_modify_success: '修改成功',
  my_modify_failed: '修改失败',
  my_wx_version_low: '微信版本过低不支持该功能',
  my_deleting: '删除中...',
  my_batch_delete: '批量删除',
  my_clear_records: '清空记录',
  my_shopping_list: '采购清单',
  my_shopping_list_title: '{mm}月{dd}日{timePrefix}的采购单',
  my_time_morning: '早上',
  my_time_noon: '中午',
  my_time_evening: '晚上',
  my_full_purchase: '完整采购汇总',
  my_initial_bill: '单',
  my_ingredients_count: '包含 {count} 种食材',
  my_initial_recipe: '菜',
  onboarding_auth_hint: '权限提示',
  onboarding_auth_location_desc: '需要授权才能推荐当地特色菜谱，是否前往设置？',
  onboarding_auth_record_desc: '需要麦克风权限才能使用语音录入，是否前往设置？',

  // 其他
  loading: '加载中...',
  success: '成功',
  fail: '失败'
};